default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['POSTGRES_PORT_5432_TCP_ADDR'] || 'localhost' %>
  port: <%= ENV['POSTGRES_PORT_5432_TCP_PORT'] || 5432 %>
  username: <%= ENV['POSTGRES_USER'] || 'lndmrk' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'lndmrk' %>
  timeout: 5000

development:
  <<: *default
  database: lndmrk_development

test:
  <<: *default
  database: lndmrk_test
