User.create({username: 'user@lndmrk.com'})

InvestmentType.create([
  { name: 'max_dividends' },
  { name: 'max_appreciation' },
  { name: 'max_dividends_appreciation' }
])
Asset.create(
  [
    {
      name: 'The Belcher\'s',
      name_heb: 'מגדלי הבלצ\'רס',
      address: '89 Pok Fu Lam Road, Pok Fu Lam/Western Mid-levels, Hong Kong',
      total: '271453',
      description: 'The Belcher\'s (Chinese: 寶翠園; Jyutping: bou2 ceoi3 jyun4) is a high-rise residential development situated in the Western Pok Fu Lam/Western Mid-levels area of Hong Kong Island. It consists of six residential buildings which were constructed in two phases; three buildings were constructed in each phase. Construction for the first phase was completed in 2000, and in 2001 for the second phase. The building was named after Sir Edward Belcher, a British naval officer and explorer, after whom a street and a bay in the area are also named, the development fronting on the former, which explains its curious name.',
      investment_type: 'max_dividends',
      market_type: 'Primary',
      property_type: 'Private,Retail',
      rating: 'A-',
      price: '14.66',
      income: '48.56',
      yield: '4',
      established: '2001',
      quality: '',
      ltv: '0.42',
      gps: '22.285556,114.133611',
      market: 'Primary',
      location: 'top in market',
      tenants_financial_stability: 'high',
      tenants_macro_stability: 'below GDP risk',
      lease_contracts_length: '12-24 months',
      contracts_securities: 'external quaranto',
      development_phase: 'full development',
      occupancy_rate: 'over 98%',
      market_occupancy_rate: 'over 90%',
      user_owned: true,
      user_watched: false,
      value: '10551',
      debt: '0',
      gains: '15666',
      image: '/images/001.png'
    },
    {
      name: 'Toyota Motor Manufacturing Canada Cambridge',
      name_heb: 'מפעל רכב- טויוטה',
      address: '1055 Fountain St N, Cambridge, ON N3H 4R7',
      total: '278709.12',
      description: 'Toyota Motor Manufacturing Canada Inc. (TMMC) is a Canada-based automotive manufacturer and is a wholly owned subsidiary of Toyota Motor Corporation. TMMC currently operates a plant in Cambridge, Ontario. In May, 2000, history was made when Toyota announced that TMMC was chosen as the first plant outside of Japan to manufacture the Lexus luxury brand of vehicles—the RX 330 SUV. Today, TMMC Cambridge South builds the third generation of that model, the RX 350, the most popular in the Lexus lineup, supplying all of North America. And, we’re still making history. On March 26, 2014, TMMC Cambridge also began building the RX 450h.',
      investment_type: 'max_dividends',
      market_type: 'Primary',
      property_type: 'Industrial',
      rating: 'B+',
      price: '2.22',
      income: '82.58',
      yield: '4.5',
      established: '1986',
      quality: '',
      ltv: '0.65',
      gps: '43.419751, -80.375373',
      market: 'Primary',
      location: 'top in market',
      tenants_financial_stability: 'high',
      tenants_macro_stability: 'above GDP risk',
      lease_contracts_length: 'over 5 years',
      contracts_securities: 'secured by business',
      development_phase: 'full development',
      occupancy_rate: 'over 98%',
      market_occupancy_rate: 'over 90%',
      user_owned: true,
      user_watched: false,
      value: '10551',
      debt: '0',
      gains: '15666',
      image: '/images/002.png'
    },
    {
      name: 'Sears Tower, Chicago, Illinois, United States',
      name_heb: 'מגדל סירס',
      address: '233 S Wacker Dr, Chicago, IL 60606, USA',
      total: '416000',
      description: 'The Willis Tower, built as and still commonly referred to as Sears Tower, is a 108-story, 1,451-foot (442 m) skyscraper in Chicago, Illinois, United States.[3] At completion in 1973, it surpassed the World Trade Center towers in New York to become the tallest building in the world, a title it held for nearly 25 years. The Willis Tower is the second-tallest building in the United States and the 14th-tallest in the world. More than one million people visit its observation deck each year, making it one of Chicago\'s most popular tourist destinations. The structure was renamed in 2009 by the Willis Group as part of its lease on a portion of the tower\'s space. As of December 2013, the building\'s largest tenant is United Airlines, which moved its corporate headquarters from the United Building at 77 West Wacker Drive in 2012 and today occupies around 20 floors with its headquarters and operations center.',
      investment_type: 'max_dividends',
      market_type: 'Primary',
      property_type: 'Retail,Office',
      rating: 'A+',
      price: '131',
      income: '58.23',
      yield: '5.10',
      established: '1973',
      quality: '',
      ltv: '35',
      gps: '41.878921, -87.635855',
      market: 'Primary',
      location: 'top in market',
      tenants_financial_stability: 'high',
      tenants_macro_stability: 'below GDP risk',
      lease_contracts_length: 'over 5 years',
      contracts_securities: 'external quaranto',
      development_phase: 'full development',
      occupancy_rate: 'over 98%',
      market_occupancy_rate: 'over 90%',
      user_owned: false,
      user_watched: true,
      value: '10551',
      debt: '0',
      gains: '15666',
      image: '/images/003.png'
    },
    {
      name: 'The Shard, London',
      name_heb: 'השארד',
      address: '32 London Bridge St, London SE1 9SG, UK',
      total: '1100',
      description: 'The Shard,[a] also referred to as the Shard of Glass,[9][10] Shard London Bridge[11] and formerly London Bridge Tower,[12][13][14] is a 95-storey skyscraper in Southwark, London, that forms part of the London BridgeQuarter development. Standing 309.6 metres (1,016 ft) high, the Shard is the tallest building in the United Kingdom, the 105th-tallest building in the world,[15] [16] and the fourth-tallest building in Europe. It is also the second-tallest free-standing structure in the United Kingdom, after the concrete tower at the Emley Moor transmitting station.',
      investment_type: 'max_appreciation',
      market_type: 'Primary',
      property_type: 'Retail,Office,Hotel',
      rating: 'A',
      price: '18.12',
      income: '78.53',
      yield: '5.2',
      established: '2012',
      quality: '',
      ltv: '45',
      gps: '51.5045, -0.0865',
      market: 'Primary',
      location: 'top in market',
      tenants_financial_stability: 'high',
      tenants_macro_stability: 'below GDP risk',
      lease_contracts_length: 'over 5 years',
      contracts_securities: 'external quaranto',
      development_phase: 'full development',
      occupancy_rate: 'over 98%',
      market_occupancy_rate: 'over 90%',
      user_owned: true,
      user_watched: false,
      value: '1051',
      debt: '0',
      gains: '15666',
      image: '/images/004.png'
    },
    {
      name: 'Lloyds Building, London',
      name_heb: 'ביניין לווידס',
      address: 'One Lime Street, London EC3M 7HA UK',
      total: '28967',
      description: 'The Lloyd\'s building (sometimes known as the Inside-Out Building)[2] is the home of the insurance institution Lloyd\'s of London. It is located on the former site of East India House in Lime Street, in London\'s main financial district, the City of London. The building is a leading example of radical Bowellism architecture in which the services for the building, such as ducts and lifts, are located on the exterior to maximise space in the interior.Twenty-five years after completion in 1986, the building received Grade I listing in 2011; it was the youngest structure ever to obtain this status. It is said by Historic England to be "universally recognised as one of the key buildings of the modern epoch".[3]',
      investment_type: 'max_dividends_appreciation',
      market_type: 'Primary',
      property_type: 'Residential',
      rating: 'A',
      price: '15.05',
      income: '66.58',
      yield: '5.3',
      established: '1998',
      quality: '',
      ltv: '65',
      gps: '3.15785, 101.71165',
      market: 'Primary',
      location: 'top in market',
      tenants_financial_stability: 'high',
      tenants_macro_stability: 'below GDP risk',
      lease_contracts_length: 'over 5 years',
      contracts_securities: 'external quaranto',
      development_phase: 'full development',
      occupancy_rate: 'over 98%',
      market_occupancy_rate: 'over 90%',
      user_owned: true,
      user_watched: false,
      value: '10551',
      debt: '0',
      gains: '15666',
      image: '/images/001.png'
    },
    {
      name: 'International Finance Centre, Hong Kong',
      name_heb: 'מרכז הסחר הבינלאומי',
      address: 'Central, Hong Kong',
      total: '185805',
      description: 'The International Finance Centre (abbr. IFC, branded as "ifc") is a skyscraper and an integrated commercial development on the waterfront of Hong Kong\'s Central District. A prominent landmark on Hong Kong Island, IFC consists of two skyscrapers, the IFC Mall, and the 55-storey Four Seasons Hotel Hong Kong. Tower 2 is the second tallest building in Hong Kong, behind the International Commerce Centre in West Kowloon. It is the fourth-tallest building in the Greater China region and the eighth-tallest office building in the world, based on structural heights; by roof height, only the Taipei 101, Shanghai World Financial Center, Willis Tower, International Commerce Centre and Burj Khalifa exceed it. It is of similar height to the former World Trade Center. The Airport Express Hong Kong Station is directly beneath it. IFC was constructed and is owned by IFC Development, a consortium of Sun Hung Kai Properties, Henderson Land and Towngas.In 2003, Financial Times, HSBC, and Cathay Pacific put up an advertisement on the facade that stretched more than 50 storeys, covering an area of 19,000 m² (0.2 million square ft) and a length of 230 m, making it the world\'s largest advertisement ever put on a skyscraper.',
      investment_type: 'max_appreciation',
      market_type: 'Secondary',
      property_type: 'Retail,Agriculture',
      rating: 'A+',
      price: '16.37',
      income: '78.38',
      yield: '5.45',
      established: '2003',
      quality: '',
      ltv: '65',
      gps: '22.285, 114.159167',
      market: 'Primary',
      location: 'top in market',
      tenants_financial_stability: 'high',
      tenants_macro_stability: 'below GDP risk',
      lease_contracts_length: 'over 5 years',
      contracts_securities: 'external quaranto',
      development_phase: 'full development',
      occupancy_rate: 'over 98%',
      market_occupancy_rate: 'over 90%',
      user_owned: false,
      user_watched: true,
      value: '10551',
      debt: '0',
      gains: '15666',
      image: '/images/002.png'
    },
    {
      name: 'World Tower, Sydney',
      name_heb: 'מגדל העולם',
      address: 'World Square, 95 Liverpool St, Sydney NSW 2000, Australia',
      total: '75565',
      description: 'World Tower is a 230 m (750 ft) skyscraper located at 91 Liverpool Street, Sydney, Australia. The building is the tallest residential building in the city since 2004. Construction began in 2001 and was completed in 2004. It was constructed by Meriton Apartments Pty Ltd, which is owned by developer Harry Triguboff. The architect was Nation Fender Katsalidis and the structural engineer was Connell Mott MacDonald.[1] World Tower was the 2004 Bronze recipient of the Emporis Skyscraper Award, and was briefly Australia\'s tallest residential building. World Tower consists of 75 above-ground levels, 10 basement levels, 15 lifts and 701 residential units. Each of the three residential sections of the building has a pool, spa, sauna, gymnasium, games room, and a private 24-seat theatrette. The pool and spa areas on levels 38 and 61 offer 180° views of Sydney. There is also a childcare centre located in the building. Situated at the foot of World Tower is World Square, a shopping complex with a Coles supermarket, several food outlets, and other specialty stores. Public buses stop outside World Square, and it is close to Town Hall and Museum railway station.',
      investment_type: 'max_dividends_appreciation',      
      market_type: 'Fringe',
      property_type: 'Commercial,Office,Agriculture',
      rating: 'A+',
      price: '8.699',
      income: '39.71',
      yield: '5.5',
      established: '2004',
      quality: '',
      ltv: '65',
      gps: '-33.876389, 151.206389',
      market: 'Primary',
      location: 'top in market',
      tenants_financial_stability: 'high',
      tenants_macro_stability: 'below GDP risk',
      lease_contracts_length: 'over 5 years',
      contracts_securities: 'external quaranto',
      development_phase: 'full development',
      occupancy_rate: 'over 98%',
      market_occupancy_rate: 'over 90%',
      user_owned: true,
      user_watched: false,
      value: '10551',
      debt: '0',
      gains: '15666',
      image: '/images/003.png'
    },
    {
      name: 'opel plant in kaiserslautern germany',
      name_heb: 'מפעל רכב - אופל',
      address: 'Opelkreisel 1, 67663 Kaiserslautern, Germany',
      total: '1540000',
      description: 'Opel is one of Europe’s largest automakers. It was founded by Adam Opel in 1862 in Rüsselsheim, Germany. Opel and its British sister brand Vauxhall sell over one million vehicles annually. In 2014 this made it the third-largest passenger car brand in the European Union. Opel is conducting the largest model offensive in its history and will introduce 27 new vehicles and 17 new engines by 2018. Opel has entered new segments with vehicles such as the compact Mokka SUV, the small lifestyle ADAM and the elegant Cascada convertible. Headquartered in Rüsselsheim, the company has 12 plants and four development and test centers in eight European countries. Opel employs around 34,500 people in Europe, with more than 16,500 in Germany. Opel and Vauxhall are present in over 50 countries. In 2014 Opel/Vauxhall sold 1.095 million passenger cars and light commercial vehicles worldwide.  The Opel Group GmbH was established effective July 1, 2014 as a sister company of Adam Opel AG. This new company is responsible for Opel/Vauxhall as well as all GM operations in Europe. The Opel Group Management Board and Chairman Dr. Karl-Thomas Neumann are also based in Rüsselsheim. The operative business of Adam Opel AG remains unaffected by this reorganization.',
      investment_type: 'max_dividends',
      market_type: 'Primary',
      property_type: 'Industrial,Commercial,Private',
      rating: 'A+',
      price: '73.43',
      income: '34.09',
      yield: '5.6',
      established: '1966',
      quality: '',
      ltv: '0.17',
      gps: '49.439803, 7.691947',
      market: 'Primary',
      location: 'top in market',
      tenants_financial_stability: 'high',
      tenants_macro_stability: 'below GDP risk',
      lease_contracts_length: 'over 5 years',
      contracts_securities: 'external quaranto',
      development_phase: 'full development',
      occupancy_rate: 'over 98%',
      market_occupancy_rate: 'over 90%',
      user_owned: true,
      user_watched: false,
      value: '10551',
      debt: '0',
      gains: '15666',
      image: '/images/004.png'
    },
    {
      name: 'Shanghai World Financial Center, China',
      name_heb: 'מרכז הסחר של שנחאי',
      address: '100 Century Ave, LuJiaZui, Pudong Xinqu, Shanghai Shi, China, 200120',
      total: '381600',
      description: 'The Shanghai World Financial Center (SWFC; Chinese: 上海环球金融中心) is a supertall skyscraper located in the Pudong district of Shanghai, China. It was designed by Kohn Pedersen Fox and developed by the Mori Building Company, with Leslie E. Robertson Associates as its structural engineer and China State Construction Engineering Corp and Shanghai Construction (Group) General Co. as its main contractor. It is a mixed-use skyscraper, consisting of offices, hotels, conference rooms, observation decks, and ground-floor shopping malls. Park Hyatt Shanghai is the tower\'s hotel component, comprising 174 rooms and suites occupying the 79th to the 93rd floors, which at the time of completion was the highest hotel in the world. It is now the third-highest hotel in the world after the Ritz-Carlton, Hong Kong, which occupies floors 102 to 108 of the International Commerce Centre.',
      investment_type: 'max_dividends',
      market_type: 'Secondary',
      property_type: 'Residential,Hotel,Industrial',
      rating: 'B+',
      price: '80.54',
      income: '39.79',
      yield: '5.8',
      established: '2008',
      quality: '',
      ltv: '0.17',
      gps: '31.236667, 121.502778',
      market: 'Primary',
      location: 'top in market',
      tenants_financial_stability: 'high',
      tenants_macro_stability: 'below GDP risk',
      lease_contracts_length: 'over 5 years',
      contracts_securities: 'external quaranto',
      development_phase: 'full development',
      occupancy_rate: 'over 98%',
      market_occupancy_rate: 'over 90%',
      user_owned: true,
      user_watched: false,
      value: '10551',
      debt: '0',
      gains: '15666',
      image: '/images/004.png'
    },
    {
      name: 'Empire State Building',
      name_heb: 'בניין אמפייר סטייט',
      address: '350 5th Ave, New York, NY 10118, USA',
      total: '2089',
      description: 'The Empire State Building is a 102-story[7][8][9][note 2] skyscraper located on Fifth Avenue between West 33rd and 34th Streets in Midtown, Manhattan, New York City. It has a roof height of 1,250 feet (381 m), and with its antenna spire included, it stands a total of 1,454 feet (443 m) high.[7] Its name is derived from the nickname for New York, the Empire State. It stood as the world\'s tallest building for nearly 40 years, from its completion in early 1931 until the topping out of the original World Trade Center\'s North Tower in late 1970.[14] Following the September 11 attacks in 2001, the Empire State Building was again the tallest building in New York, until One World Trade Center reached a greater height in April 2012.[15] The Empire State Building is currently the fifth-tallest completed skyscraper in the United States and the 29th-tallest in the world. It is also the fifth-tallest freestanding structure in the Americas. When measured by pinnacle height, it is the fourth-tallest building in the United States.',
      market_type: 'Primary',
      investment_type: 'max_appreciation',
      property_type: 'Retail,Office',
      rating: 'A+',
      price: '16.99',
      income: '81.29',
      yield: '5.9',
      established: '2008',
      quality: '',
      ltv: '0.17',
      gps: '40.748433, -73.985656',
      market: 'Primary',
      location: 'top in market',
      tenants_financial_stability: 'high',
      tenants_macro_stability: 'below GDP risk',
      lease_contracts_length: 'over 5 years',
      contracts_securities: 'external quaranto',
      development_phase: 'full development',
      occupancy_rate: 'over 98%',
      market_occupancy_rate: 'over 90%',
      user_owned: false,
      user_watched: true,
      value: '10551',
      debt: '0',
      gains: '15666',
      image: '/images/004.png'
    },
    {
      name: 'Chrysler Building, NYC',
      name_heb: 'בניין קרייזלר',
      address: 'Lexington Ave, New York, NY 10174, USA',
      total: '1110',
      description: 'The Chrysler Building is an Art Deco-style skyscraper located on the East Side of Midtown Manhattan in New York City, at the intersection of 42nd Street and Lexington Avenue in the Turtle Bay neighborhood. At 1,046 feet (319 m), the structure was the world\'s tallest building for 11 months before it was surpassed by the Empire State Building in 1931.[9] It is the tallest brick building in the world, albeit with a steel frame. After the destruction of the World Trade Center, it was again the second-tallest building in New York City until December 2007, when the spire was raised on the 1,200-foot (365.8 m) Bank of America Tower, pushing the Chrysler Building into third position. In addition, The New York Times Building, which opened in 2007, is exactly level with the Chrysler Building in height.[10] Both buildings were then pushed into fourth position, when the under-construction One World Trade Center surpassed their height, and then to fifth position by 432 Park Avenue which was completed in 2015.',
      market_type: 'Secondary',
      investment_type: 'max_dividends_appreciation',
      property_type: 'Office',
      rating: 'A+',
      price: '16.53',
      income: '81.29',
      yield: '5.9',
      established: '2008',
      quality: '',
      ltv: '0.17',
      gps: '40.752128, -73.975571',
      market: 'Fringe',
      location: 'top in market',
      tenants_financial_stability: 'high',
      tenants_macro_stability: 'below GDP risk',
      lease_contracts_length: 'over 5 years',
      contracts_securities: 'external quaranto',
      development_phase: 'full development',
      occupancy_rate: 'over 98%',
      market_occupancy_rate: 'over 90%',
      user_owned: false,
      user_watched: true,
      value: '10551',
      debt: '0',
      gains: '15666',
      image: '/images/004.png'
    },
  ]
)

Setting.create({ key: 'Locale', value: 'en_us' })
